name: build containers
on:
  push:
    branches:
      - master
jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - { CONTEXT: "./ce/jre", PREFIX: "jre-ce", IMAGE: "8" }
          - { CONTEXT: "./ce/jre", PREFIX: "jre-ce", IMAGE: "11" }
          - { CONTEXT: "./ce/jre", PREFIX: "jre-ce", IMAGE: "17" }
          - { CONTEXT: "./ce/jdk", PREFIX: "jdk-ce", IMAGE: "8" }
          - { CONTEXT: "./ce/jdk", PREFIX: "jdk-ce", IMAGE: "11" }
          - { CONTEXT: "./ce/jdk", PREFIX: "jdk-ce", IMAGE: "17" }
          - { CONTEXT: "./ee/jre", PREFIX: "jre-ee", IMAGE: "8" }
          - { CONTEXT: "./ee/jre", PREFIX: "jre-ee", IMAGE: "11" }
          - { CONTEXT: "./ee/jre", PREFIX: "jre-ee", IMAGE: "17" }
          - { CONTEXT: "./ee/jdk", PREFIX: "jdk-ee", IMAGE: "j8" }
          - { CONTEXT: "./ee/jdk", PREFIX: "jdk-ee", IMAGE: "11" }
          - { CONTEXT: "./ee/jdk", PREFIX: "jdk-ee", IMAGE: "17" }
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/login-action@v2
        with:
          registry: container-registry.oracle.com
          username: ${{ secrets.ORACLE_SSO_USERNAME }}
          password: ${{ secrets.ORACLE_SSO_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./
          file: ${{ matrix.tag.CONTEXT }}/${{ matrix.tag.IMAGE }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sersoid/pterodactyl-graalvm:${{ matrix.tag.PREFIX }}-${{ matrix.tag.IMAGE }}
